learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/',include('users.urls',namespace='users')),#创建用户账号
    path('',include('learning_logs.urls',namespace='learning_logs')),
]

learning_logs/urls.py
"""定义learning_logs的URL模式"""
from django.urls import path  

from . import views 

app_name = 'learning_logs' 

urlpatterns = [
    #主页
    path('',views.index,name='index'),
    #显示所有主题
    path('topic/',views.topics,name='topics'),
    #特定主题的详细页面,新版为<>定义转换器
    path('topics/<int:topic_id>/',views.topic,name='topic'),
    #用于添加新主题的网页
    path('new_topic/',views.new_topic,name='new_topic'),
    #用于添加新条目的页面
    path('new_entry/<int:topic_id>/',views.new_entry,name='new_entry'),
    #用于编辑条目的页面
    path('edit_entry/<int:entry_id>/',views.edit_entry,name='edit_entry'),
    # 显示公共主题
    path('public_topics/', views.public_topics, name='public_topics'),
    
]

users/urls.py
"""为应用程序users定义URL模式"""
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views 

app_name = 'users'

urlpatterns = [
    #登陆界面
    path('login/',LoginView.as_view(template_name='users/login.html'), name='login'),
    #注销
    path('logout/',views.logout_view,name='logout'),
    #注册页面
    path('register',views.register,name='register'),
    
]

learning_logs/models.py
from django.db import models
#关联用户
from django.contrib.auth.models import User

class Topic(models.Model):
    """用户学习的主题"""
    #设置200字符
    text = models.CharField(max_length = 200)
    #记录日期和时间
    date_added = models.DateTimeField(auto_now_add=True)
    #关联用户
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    #设置公开属性
    public = models.BooleanField(default=False)

    
    def __str__(self):
        """返回模型的字符串表示"""
        #添加主题与所有者的名字
        return f"{self.text} by {self.owner.username}"

class Entry(models.Model):
    """学到的有关莫个主题的具体知识"""
    #外键引用数据库中的林外一个记录，将两者关联
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)  # 添加 on_delete 参数是Django 2.0+ 的推荐做法 
    text = models.TextField()
    #按照创建顺序显示条目，并将每个条目旁加入时间辍
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        #用Entries表示多个条目，而不是Entrys
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        #18-2如果长度少于50,没有省略号
        if len(self.text) <= 50:
            return self.text
        else:#显示前50字符，并添加省略号
            return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text','public']
        labels = {'text': '','public':''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

learning_logs/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic,Entry
from .forms import TopicForm,EntryForm

def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

def public_topics(request):
    """显示公开的主题"""
    topics = list(Topic.objects.all().order_by('-date_added'))
    for topic in topics[:]:
        if topic.public == False:
            topics.remove(topic)
 
    context = {'topics': topics}
    return render(request, 'learning_logs/public.html', context)

#查看限制，需要登陆
@login_required
def topics(request):
    """显示所有主题"""
    #用户只能看到自己的主题
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'learning_logs/topics.html',context)

#查看限制，需要登陆
@login_required
def topic(request,topic_id):
    """显示单个主题及其所有的条目"""
    #修改
    topic = get_object_or_404(Topic,id=topic_id)
    if topic.public == False:
        check_topic_owner(topic,request)
        
    entries = topic.entry_set.order_by('date_added')
    context = {'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)


#查看限制，需要登陆
@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        #为提交数据：船舰一个新表单
        form = TopicForm()
    else:
        #POST提交的数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
    context = {'form':form}
    return render(request,'learning_logs/new_topic.html',context)
    
#查看限制，需要登陆
@login_required
def new_entry(request,topic_id):
    """在特定的主题中添加新条目"""
    #修改
    topic = get_object_or_404(Topic,id=topic_id)
    if request.method != 'POST':
        #未提交数据，创建一个空表单
        form = EntryForm()
    else:
        #POST提交的数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
    context = {'topic':topic,'form':form}
    return render(request,'learning_logs/new_entry.html',context)


#查看限制，需要登陆
@login_required
def edit_entry(request,entry_id):
    """编辑现有条目"""
    entry = get_object_or_404(Entry,id=entry_id)
    topic= entry.topic
    #确认请求的主题属于当前用户
    check_topic_owner(topic,request)
        
    if request.method != 'POST':
        #初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        #POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    context = {'entry':entry,'topic':topic,'form':form}
    return render(request,'learning_logs/edit_entry.html',context)
#19-3重构
def check_topic_owner(topic,request):
    """核实用户"""
    #确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm



def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """注册新用户"""
    if request.method !='POST':
        #显示空的注册表单
        form = UserCreationForm()
    else:
        #处理写好的表单
        form = UserCreationForm(request.POST)#可以不用data

        if form.is_valid():
            new_user = form.save()
            #让用户自动登陆，再重新定向到主页
            authenticated_user = authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context = {'form':form}
    return render(request,'users/register.html',context)

learning_logs/templates/learning_logs/.ipynb_checkpoints/base-checkpoint.html
<p>
    <a href="{% url 'learning_logs:index'%}">learning log</a>
    <a href="{% url 'learning_logs:topics'%}">Topics</a>
  </p>
  {%block content %}{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    
    
   <title>Learning Log</title>
   
   {% bootstrap_css %}
   {% bootstrap_javascript jquery='full' %}
  </head>
  
  <body>
  
    <!--Static navbar -->
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>  
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">  

          <ul class="navbar-nav mr-auto">  

            <li class="nav-item">  

              <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>  

            </li>  
            <li class="nav-item">
            <a class="nav-link" href="{% url 'learning_logs:public_topics' %}"> Public Topics</a>
            </li>

          </ul>  

          <ul class="navbar-nav ml-auto">  

            {% if user.is_authenticated %}  

              <li class="nav-item">  

                <span class="navbar-text">Hello, {{ user.username }}.</span>  

              </li>  

              <li class="nav-item">  

                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>  

              </li>  

            {% else %}  

              <li class="nav-item">  

                <a class="nav-link" href="{% url 'users:register' %}">Register</a>  

              </li>  

              <li class="nav-item">  

                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>  

              </li>  

            {% endif %}  

          </ul>  

        </div>  


    </nav>  
    
    <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </main> 
    

  </body>
  
</html>


          
        

learning_logs/templates/learning_logs/edit_entry.html
{%extends "learning_logs/base.html" %}
{% load bootstrap4 %}
{% block header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic}}</a></h2>
  <h3> Edit Entry:</h3>
{% endblock header %}

{%block content %}

   <form action="{% url 'learning_logs:edit_entry' entry.id %}"method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
     <button type="submit">Save Changes</button>
    {% endbuttons %}
    
   </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Track your learning.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log, and list the topics you're learning about.Afterward, you can decide whether to make it public or keep it private.
  </h2>
  <h2>
    Whenever you learn somthing new about a topic, make an entry summarizing what you've learned.
  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{%extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
  <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic}}</a></h2>
  <h3> Add a New Entry:</h3>
{% endblock header %}

{%block content %}

   <form action="{% url 'learning_logs:new_entry' topic.id %}"method='post' class="form">
     {%csrf_token%}
     {% bootstrap_form form %}
     
     
     {% buttons %}
       <button name="submit" class="btn btn-primary">Add New Entry</button>
     {% endbuttons %}
     
   </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
  <h2>Add a New Topic </h2>
{% endblock header %}

{%block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method='post' class ="form">
  
     {% csrf_token %}
     {% bootstrap_field form.text show_label=True %} 
     
    <div class="form-group">  

        <div class="form-check">  

            <input type="checkbox" class="form-check-input" id="id_public" name="public">  

            <label class="form-check-label" for="id_public">Public</label>  

        </div>  

    </div> 
      <button type="submit" class="btn btn-primary">Add New Topic</button>
   </form>

{% endblock content %}

learning_logs/templates/learning_logs/public.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Public Topics</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>   
      </li>
    {% empty %}
      <li><h3>No Public topics have been added yet.</h3></li>
    {% endfor %}
   </ul>
   
 {% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h3>{{ topic }}</h3>
  {% if user == topic.owner %}
  <h5>Public: {{ topic.public }}</h2>
  {% endif %}
{% endblock header %}

{% block content %}
  {% if user == topic.owner %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  {% endif %}
  
    {% for entry in entries %}
      <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'M d, Y H:i' }}
        {% if user == topic.owner %}
            <small>
              <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
            </small>
        {% endif %}
          </h4>
        <div class="card-body">
          {{ entry.text|linebreaks }}
        </div>
      </div><!-- card -->
    {% empty %}
      <p>There are no entries for this topic yet.</p>
    {% endfor %}
   
 {% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for topic in topics %}
      <li>
        <h3>
          <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </h3>   
      </li>
    {% empty %}
      <li><h3>No topics have been added yet.</h3></li>
    {% endfor %}
   </ul>
   
    <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a></h3>
   
 {% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
  <h2> Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
  
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
  <h2>Register<h2>
{% endblock header %}

{% block content %}
  <form method="post" action="{% url 'users:register' %}" class ="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    
    {% buttons %}
      <button name="submit">register</button>
    {% endbuttons %}
    
    <input type="hidden" name='next' value="{% url 'learning_logs:index' %}" />
  </form>
  
{% endblock content %}
  
  